version: "3"

services:

  access-sdk-csharp-preview-build:
    build: .
    container_name: access-sdk-csharp-preview-build
    image: finbourne/access-sdk-csharp-preview-build
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_ACCESS_API_URL
      - FBN_APP_NAME
    volumes:
      - .:/usr/src